version: 2.1
jobs:
  build-ubuntu-arm64:
    steps:
    - checkout
    - run:
        command: |2-
            #!/usr/bin/env bash
            set -eo pipefail

            # install jdk
            curl -L \
              https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.20.1_1.tar.gz -o /tmp/jdk.tar.gz

            tar tf /tmp/jdk.tar.gz
            mkdir ~/jdk \
            && cd ~/jdk \
            && cat /tmp/jdk.tar.gz | tar --strip-components=1 -xzC .

            mkdir -p ~/staticdeps/bin

            # install zlib
            mkdir -p /tmp/dep_zlib-1.2.13 \
            && cd /tmp/dep_zlib-1.2.13 \
            && cat /tmp/zlib.tar.gz | tar --strip-components=1 -xzC . \
            && echo "zlib-1.2.13: configure..." && ./configure --static --prefix=~/staticdeps > /dev/null \
            && echo "zlib-1.2.13: make..." && make -s -j4 \
            && echo "zlib-1.2.13: make install..." && make -s install \
            && rm -rf /tmp/dep_zlib-1.2.13

            export PATH=~/staticdeps/bin:$PATH >> "$BASH_ENV"
        name: Set up environment
    - run:
        command: |-
          export PATH=/staticdeps/bin:$PATH
          export JAVA_HOME=~/jdk/
          ./gradlew --info --stacktrace '-Dorg.gradle.jvmargs=-Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' buildNative
        name: gradle buildNative
    - persist_to_workspace:
        root: '.'
        paths:
        - pkl-cli/build/executable/
    resource_class: arm.medium
    machine:
      image: ubuntu-2204:current
workflows:
  build-native-images:
    jobs:
    - build-ubuntu-arm64:
        filters:
          branches:
            only: main
