version: 2.1
jobs:
  build-linux-amd64:
    steps:
    - checkout
    - restore_cache:
        key: gradle-dependencies-{{ checksum "gradle/libs.versions.toml" }}
        name: Restore Gradle Dependencies Cache
    - restore_cache:
        key: staticdeps-amd64
        name: Restore static deps from cache
    - run:
        command: |-
          sed -ie '/\[ol8_codeready_builder\]/,/^$/s/enabled=0/enabled=1/g' /etc/yum.repos.d/oracle-linux-ol8.repo \
            && microdnf -y install util-linux tree coreutils-single findutils curl tar gzip git zlib-devel gcc-c++ make openssl glibc-langpack-en libstdc++-static \
            && microdnf clean all \
            && rm -rf /var/cache/dnf

          # install jdk
          curl -L \
           https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.20.1_1.tar.gz -o /tmp/jdk.tar.gz

          mkdir ~/jdk \
            && cd ~/jdk \
            && cat /tmp/jdk.tar.gz | tar --strip-components=1 -xzC .

          mkdir -p ~/staticdeps/bin

          cp /usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.a ~/staticdeps

          # install zlib
          if [[ ! -f ~/staticdeps/include/zlib.h ]]; then
            curl -L https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz -o /tmp/zlib.tar.gz

            mkdir -p /tmp/dep_zlib-1.2.13 \
            && cd /tmp/dep_zlib-1.2.13 \
            && cat /tmp/zlib.tar.gz | tar --strip-components=1 -xzC . \
            && echo "zlib-1.2.13: configure..." && ./configure --static --prefix="$HOME"/staticdeps > /dev/null \
            && echo "zlib-1.2.13: make..." && make -s -j4 \
            && echo "zlib-1.2.13: make install..." && make -s install \
            && rm -rf /tmp/dep_zlib-1.2.13
          fi

          # install musl
          if [[ ! -f ~/staticdeps/bin/x86_64-linux-musl-gcc ]]; then
            curl -L https://musl.libc.org/releases/musl-1.2.2.tar.gz -o /tmp/musl.tar.gz

            mkdir -p /tmp/dep_musl-1.2.2 \
            && cd /tmp/dep_musl-1.2.2 \
            && cat /tmp/musl.tar.gz | tar --strip-components=1 -xzC . \
            && echo "musl-1.2.2: configure..." && ./configure --disable-shared --prefix="$HOME"/staticdeps > /dev/null \
            && echo "musl-1.2.2: make..." && make -s -j4 \
            && echo "musl-1.2.2: make install..." && make -s install \
            && rm -rf /tmp/dep_musl-1.2.2

            # native-image expects to find an executable at this path.
            ln -s ~/staticdeps/bin/musl-gcc ~/staticdeps/bin/x86_64-linux-musl-gcc
          fi
        name: Set up environment
        shell: '#!/bin/bash -exo pipefail'
    - save_cache:
        paths:
        - ~/staticdeps
        key: staticdeps-amd64
        name: Save statics deps to cache
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_cacheing: true
    - run:
        command: |-
          export JAVA_HOME=~/jdk
          export PATH=~/staticdeps/bin:$PATH
          ./gradlew --info --stacktrace '-Dorg.gradle.jvmargs=-Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' pkl-cli:linuxExecutableAmd64 pkl-cli:testLinuxExecutableAmd64
        name: gradle pkl-cli:linuxExecutableAmd64 pkl-cli:testLinuxExecutableAmd64
    - save_cache:
        paths:
        - ~/.gradle/caches/modules-2/files-2.1/
        key: gradle-dependencies-{{ checksum "gradle/libs.versions.toml" }}
        name: Save Gradle Dependencies Cache
    - persist_to_workspace:
        root: '.'
        paths:
        - pkl-cli/build/executable/
    - run: cat */build/test-results/**.xml > build/test-results.xml
    - store_test_results:
        path: build/test-results.xml
    resource_class: large
    docker:
    - image: oraclelinux:8-slim
  build-linux-arm64:
    steps:
    - checkout
    - restore_cache:
        key: gradle-dependencies-{{ checksum "gradle/libs.versions.toml" }}
        name: Restore Gradle Dependencies Cache
    - restore_cache:
        key: staticdeps-aarch64
        name: Restore static deps from cache
    - run:
        command: |-
          sed -ie '/\[ol8_codeready_builder\]/,/^$/s/enabled=0/enabled=1/g' /etc/yum.repos.d/oracle-linux-ol8.repo \
            && microdnf -y install util-linux tree coreutils-single findutils curl tar gzip git zlib-devel gcc-c++ make openssl glibc-langpack-en libstdc++-static \
            && microdnf clean all \
            && rm -rf /var/cache/dnf

          # install jdk
          curl -L \
           https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.20.1_1.tar.gz -o /tmp/jdk.tar.gz

          mkdir ~/jdk \
            && cd ~/jdk \
            && cat /tmp/jdk.tar.gz | tar --strip-components=1 -xzC .

          mkdir -p ~/staticdeps/bin

          cp /usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.a ~/staticdeps

          # install zlib
          if [[ ! -f ~/staticdeps/include/zlib.h ]]; then
            curl -L https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz -o /tmp/zlib.tar.gz

            mkdir -p /tmp/dep_zlib-1.2.13 \
            && cd /tmp/dep_zlib-1.2.13 \
            && cat /tmp/zlib.tar.gz | tar --strip-components=1 -xzC . \
            && echo "zlib-1.2.13: configure..." && ./configure --static --prefix="$HOME"/staticdeps > /dev/null \
            && echo "zlib-1.2.13: make..." && make -s -j4 \
            && echo "zlib-1.2.13: make install..." && make -s install \
            && rm -rf /tmp/dep_zlib-1.2.13
          fi
        name: Set up environment
        shell: '#!/bin/bash -exo pipefail'
    - save_cache:
        paths:
        - ~/staticdeps
        key: staticdeps-aarch64
        name: Save statics deps to cache
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_cacheing: true
    - run:
        command: |-
          export JAVA_HOME=~/jdk
          export PATH=~/staticdeps/bin:$PATH
          ./gradlew --info --stacktrace '-Dorg.gradle.jvmargs=-Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' pkl-cli:linuxExecutableAarch64 pkl-cli:testLinuxExecutableAarch64
        name: gradle pkl-cli:linuxExecutableAarch64 pkl-cli:testLinuxExecutableAarch64
    - save_cache:
        paths:
        - ~/.gradle/caches/modules-2/files-2.1/
        key: gradle-dependencies-{{ checksum "gradle/libs.versions.toml" }}
        name: Save Gradle Dependencies Cache
    - persist_to_workspace:
        root: '.'
        paths:
        - pkl-cli/build/executable/
    - run: cat */build/test-results/**.xml > build/test-results.xml
    - store_test_results:
        path: build/test-results.xml
    resource_class: large
    docker:
    - image: arm64v8/oraclelinux:8-slim
  build-linux-alpine-amd64:
    steps:
    - checkout
    - restore_cache:
        key: gradle-dependencies-{{ checksum "gradle/libs.versions.toml" }}
        name: Restore Gradle Dependencies Cache
    - restore_cache:
        key: staticdeps-amd64
        name: Restore static deps from cache
    - run:
        command: |-
          sed -ie '/\[ol8_codeready_builder\]/,/^$/s/enabled=0/enabled=1/g' /etc/yum.repos.d/oracle-linux-ol8.repo \
            && microdnf -y install util-linux tree coreutils-single findutils curl tar gzip git zlib-devel gcc-c++ make openssl glibc-langpack-en libstdc++-static \
            && microdnf clean all \
            && rm -rf /var/cache/dnf

          # install jdk
          curl -L \
           https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.20.1_1.tar.gz -o /tmp/jdk.tar.gz

          mkdir ~/jdk \
            && cd ~/jdk \
            && cat /tmp/jdk.tar.gz | tar --strip-components=1 -xzC .

          mkdir -p ~/staticdeps/bin

          cp /usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.a ~/staticdeps

          # install zlib
          if [[ ! -f ~/staticdeps/include/zlib.h ]]; then
            curl -L https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz -o /tmp/zlib.tar.gz

            mkdir -p /tmp/dep_zlib-1.2.13 \
            && cd /tmp/dep_zlib-1.2.13 \
            && cat /tmp/zlib.tar.gz | tar --strip-components=1 -xzC . \
            && echo "zlib-1.2.13: configure..." && ./configure --static --prefix="$HOME"/staticdeps > /dev/null \
            && echo "zlib-1.2.13: make..." && make -s -j4 \
            && echo "zlib-1.2.13: make install..." && make -s install \
            && rm -rf /tmp/dep_zlib-1.2.13
          fi

          # install musl
          if [[ ! -f ~/staticdeps/bin/x86_64-linux-musl-gcc ]]; then
            curl -L https://musl.libc.org/releases/musl-1.2.2.tar.gz -o /tmp/musl.tar.gz

            mkdir -p /tmp/dep_musl-1.2.2 \
            && cd /tmp/dep_musl-1.2.2 \
            && cat /tmp/musl.tar.gz | tar --strip-components=1 -xzC . \
            && echo "musl-1.2.2: configure..." && ./configure --disable-shared --prefix="$HOME"/staticdeps > /dev/null \
            && echo "musl-1.2.2: make..." && make -s -j4 \
            && echo "musl-1.2.2: make install..." && make -s install \
            && rm -rf /tmp/dep_musl-1.2.2

            # native-image expects to find an executable at this path.
            ln -s ~/staticdeps/bin/musl-gcc ~/staticdeps/bin/x86_64-linux-musl-gcc
          fi
        name: Set up environment
        shell: '#!/bin/bash -exo pipefail'
    - save_cache:
        paths:
        - ~/staticdeps
        key: staticdeps-amd64
        name: Save statics deps to cache
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_cacheing: true
    - run:
        command: |-
          export JAVA_HOME=~/jdk
          export PATH=~/staticdeps/bin:$PATH
          ./gradlew --info --stacktrace '-Dorg.gradle.jvmargs=-Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' pkl-cli:alpineExecutableAmd64 pkl-cli:testAlpineExecutableAmd64
        name: gradle pkl-cli:alpineExecutableAmd64 pkl-cli:testAlpineExecutableAmd64
    - save_cache:
        paths:
        - ~/.gradle/caches/modules-2/files-2.1/
        key: gradle-dependencies-{{ checksum "gradle/libs.versions.toml" }}
        name: Save Gradle Dependencies Cache
    - persist_to_workspace:
        root: '.'
        paths:
        - pkl-cli/build/executable/
    - run: cat */build/test-results/**.xml > build/test-results.xml
    - store_test_results:
        path: build/test-results.xml
    resource_class: large
    docker:
    - image: oraclelinux:8-slim
  build-macos-amd64:
    steps:
    - checkout
    - restore_cache:
        key: gradle-dependencies-{{ checksum "gradle/libs.versions.toml" }}
        name: Restore Gradle Dependencies Cache
    - run:
        command: |-
          export JAVA_HOME=~/jdk
          export PATH=~/staticdeps/bin:$PATH
          ./gradlew --info --stacktrace '-Dorg.gradle.jvmargs=-Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' buildNative
        name: gradle buildNative
    - save_cache:
        paths:
        - ~/.gradle/caches/modules-2/files-2.1/
        key: gradle-dependencies-{{ checksum "gradle/libs.versions.toml" }}
        name: Save Gradle Dependencies Cache
    - persist_to_workspace:
        root: '.'
        paths:
        - pkl-cli/build/executable/
    macos:
      xcode: 14.0.0
workflows:
  build-native-images:
    jobs:
    - build-linux-arm64:
        filters:
          branches:
            only: main
    - build-linux-amd64:
        filters:
          branches:
            only: main
    - build-linux-alpine-amd64:
        filters:
          branches:
            only: main
