version: 2.1
jobs:
  build-ubuntu-arm64:
    steps:
    - checkout
    - run:
        command: |2-
            #!/usr/bin/env bash
            set -eo pipefail

            # install system deps
            # sed -ie '/\[ol8_codeready_builder\]/,/^$/s/enabled=0/enabled=1/g' /etc/yum.repos.d/oracle-linux-ol8.repo \
            # && microdnf -y install util-linux tree coreutils-single findutils curl tar gzip git zlib-devel gcc-c++ make openssl glibc-langpack-en libstdc++-static \
            # && microdnf clean all

            # install jdk11
            curl -L \
              https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz -o /tmp/openjdk11.tar.gz

            tar tf /tmp/openjdk11.tar.gz
            mkdir ~/jdk11 \
            && cd ~/jdk11 \
            && cat /tmp/openjdk11.tar.gz | tar --strip-components=1 -xzC .

            mkdir -p ~/staticdeps/bin

            # install libstdc
            # mkdir ~/staticdeps \
            # && cp /usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.a ~/staticdeps \

            # native-image expects to find an executable at this path.
            ln -s ~/staticdeps/bin/musl-gcc ~/staticdeps/bin/aarch64-linux-musl-gcc

            # install zlib
            mkdir -p /tmp/dep_zlib-1.2.13 \
            && cd /tmp/dep_zlib-1.2.13 \
            && cat /tmp/zlib.tar.gz | tar --strip-components=1 -xzC . \
            && echo "zlib-1.2.13: configure..." && ./configure --static --prefix=~/staticdeps > /dev/null \
            && echo "zlib-1.2.13: make..." && make -s -j4 \
            && echo "zlib-1.2.13: make install..." && make -s install \
            && rm -rf /tmp/dep_zlib-1.2.13

            export PATH=~/staticdeps/bin:$PATH >> "$BASH_ENV"
        name: Set up environment
    - run:
        command: |-
          export PATH=/staticdeps/bin:$PATH
          ./gradlew --info --stacktrace '-Dorg.gradle.jvmargs=-Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' buildNative
        name: gradle buildNative
    - persist_to_workspace:
        root: '.'
        paths:
        - pcl-cli/build/executable/
    resource_class: arm.medium
    machine:
      image: ubuntu-2204:current
workflows:
  build-native-images:
    jobs:
    - build-ubuntu-arm64:
        filters:
          branches:
            only: main
